import Head from 'next/head';
import HeroSection from '../components/HeroSection';
import DownloadOptions from '../components/DownloadOptions';
import Features from '../components/Features';
import Screenshots from '../components/Screenshots';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    
    <div className={styles.container}>
      <Head>
        <title>My Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroSection />
      <DownloadOptions />
      <Features />
      <Screenshots />
    </div>
  );
}
